name: pfmbench
channels:
  - pytorch
  - nvidia
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.3
  - aria2=1.37.0
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2025.1.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.0
  - cmake=3.5.0
  - colorama=0.4.6
  - conda=22.9.0
  - conda-build=3.26.1
  - conda-index=0.5.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=44.0.1
  - cuda-cudart=11.8.89
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - faiss-gpu=1.8.0
  - filelock=3.16.1
  - fmt=9.1.0
  - frozendict=2.4.6
  - gawk=5.3.1
  - glob2=0.7
  - gmp=6.3.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.4.5
  - intel-openmp=2025.0.0
  - ipython=8.29.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.43
  - libarchive=3.6.2
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcurl=8.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libfaiss=1.8.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgpg-error=1.53
  - libhwloc=2.11.2
  - libiconv=1.17
  - liblapack=3.9.0
  - liblief=0.14.1
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libmamba=1.4.9
  - libmambapy=1.4.9
  - libnghttp2=1.58.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpmix=5.0.7
  - libsolv=0.7.32
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libudev1=257.4
  - libuuid=2.38.1
  - libuv=1.49.2
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.9
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - menuinst=2.1.2
  - mkl=2023.2.0
  - mmseqs2=17.b804f
  - more-itertools=10.5.0
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openmpi=5.0.7
  - openssl=3.4.0
  - packaging=24.1
  - parso=0.8.4
  - patch=2.7.6
  - patchelf=0.17.2
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkginfo=1.11.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-lief=0.14.1
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.18.0
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-libarchive-c=5.1
  - python_abi=3.11
  - pytz=2024.2
  - pyyaml=6.0.2
  - rdma-core=55.0
  - readline=8.2
  - referencing=0.35.1
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rhash=1.4.5
  - ripgrep=14.1.1
  - rpds-py=0.20.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.15.80
  - simdjson=3.11.6
  - six=1.16.0
  - soupsieve=2.5
  - spdlog=1.12.0
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.13
  - toolz=1.0.0
  - traitlets=5.14.3
  - truststore=0.9.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - ucc=1.3.0
  - ucx=1.18.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - pip:
    - absl-py==2.1.0
    - accelerate==1.3.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.12
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.8.0
    - apex==0.9.8.dev0 #0.1
    - appdirs==1.4.4
    - astunparse==1.6.3
#    - bioft #==1.0
    - biopandas==0.5.1
    - biopython==1.85
    - bioservices==1.12.1
    - biotite==0.41.2
    - biotraj==1.2.2
    - braceexpand==0.1.7
    - cattrs==24.1.3
    - click==8.1.8
    - cloudpathlib==0.20.0
    - colorlog==6.9.0
   # - conda-libmamba-solver==25.1.1
    - contourpy==1.3.1
    - cpdb-protein==0.2.0
    - cycler==0.12.1
    - cython==3.0.12
    - debugpy==1.8.12
    - deepdiff==8.4.2
    - deepspeed==0.16.3
    - dnspython==2.7.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - easydev==0.13.3
    - einops==0.8.0
    - expecttest==0.2.1
   # - flash-attn==2.7.2.post1
    - flatbuffers==25.2.10
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - gast==0.6.0
    - gemmi==0.7.1
    - gevent==24.11.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-pasta==0.2.0
    - graphein==1.7.7
    - greenlet==3.2.0
    - grequests==0.7.0
    - grpcio==1.70.0
    - h11==0.14.0
    - h5py==3.13.0
    - hjson==3.1.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.28.0
    - hydra-core==1.3.2
    - hypothesis==6.115.5
    - iopath==0.1.10
    - jaxtyping==0.3.1
    - jiter==0.8.2
    - joblib==1.4.2
    - keras==3.9.2
    - kiwisolver==1.4.8
    - libclang==18.1.1
    - lightning==2.5.0.post0
    - lightning-utilities==0.12.0
    - line-profiler==4.2.0
    - lintrunner==0.12.5
    - lmdb==1.6.2
    - loguru==0.7.3
    - looseversion==1.1.2
    - lxml==5.3.2
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.10.1
    - mc-bin-client==1.0.1
    - mdurl==0.1.2
    - megatron-core==0.2.0
    - mini3di==0.2.1
    - ml-dtypes==0.5.1
    - mmtf-python==1.1.3
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgpack-numpy==0.4.8
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - mypy-extensions==1.0.0
    - namex==0.0.8
    - narwhals==1.35.0
    - networkx==3.4.2
    - ninja==1.11.1.1
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-ml-py
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - omegaconf==2.3.0
    - openai==1.64.0
    - opt-einsum==3.4.0
    - optree==0.13.0
    - orderly-set==5.4.0
    - pandas==2.2.3
    - peft==0.14.0
    - pillow==10.2.0
    - plotly==6.0.1
    - portalocker==3.1.1
    - propcache==0.2.1
    - protobuf==5.29.3
    - py-cpuinfo==9.0.0
    - pybind11==2.14.0.dev1
    - pydantic==2.10.6
    - pydantic-core==2.27.2
   # - pyg-lib==0.4.0+pt25cu121
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - python-etcd==0.4.5
    - pytorch-lightning==2.5.0.post0
    - rdkit==2024.9.6
    - rdkit-pypi==2022.9.5
    - regex==2024.11.6
    - requests-cache==1.2.1
    - rich==14.0.0
    - rich-click==1.8.8
    - safetensors==0.5.2
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.20.0
    - setproctitle==1.3.4
    - setuptools==72.1.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - suds-community==1.2.0
    - sympy==1.13.1
    - tenacity==9.1.2
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.19.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.0.1
    - tf-keras==2.19.0
    - threadpoolctl==3.5.0
    - timm==1.0.15
    - tokenizers==0.21.0
    - torch==2.5.1 #+cu121
 #   - torch-cluster==1.6.3 #+pt25cu121
    - torch-geometric==2.6.1
 #   - torch-scatter==2.1.2 #+pt25cu121
 #   - torch-sparse==0.6.18+pt25cu121
#    - torch-spline-conv==1.2.2+pt25cu121
    - torchaudio==2.5.1 #+cu121
    - torchelastic==0.2.2
    - torchmetrics==1.6.1
    - torchvision==0.20.1 #+cu121
    #- flash-attn==2.7.2.post1
    - tqdm==4.67.1
    - transformers==4.48.1
    - triton==3.1.0
    - typed-argument-parser==1.10.1
    - types-dataclasses==0.6.6
    - typing-inspect==0.9.0
    - tzdata==2025.1
    - url-normalize==2.2.0
    - vplm==0.0.1
    - wadler-lindig==0.1.5
    - wandb==0.19.5
    - webdataset==0.2.111
    - werkzeug==3.1.3
    - wget==3.2
    - wrapt==1.17.2
    - xarray==2025.3.1
    - xmltodict==0.14.2
    - yarl==1.18.3
    - zope-event==5.0
    - zope-interface==7.2
    - zstd==1.5.6.6
    - flash-attn
    - torch-cluster
    - torch-sparse
    - torch-spline-conv