# Configuration for inference on SE(3) diffusion experiments.
task: scaffold
inference:
  workspace: ../../workspace
  name: null
  gpu_id: null  # CUDA GPU to use
  seed: 123
  # Directory of software, weights, and outputs.
  pmpnn_dir: ../../ProteinMPNN/



  samples:
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8

