Output:
  res_dir: "tasks/results/esol"
  ex_name: "esol_adapter"
  offline: ${eval:"int(${oc.env:OFFLINE, '1'})"}

Data:
  train_data_path: "/nfs_beijing/kubeflow-user/zhangyang_2024/workspace/protein_benchmark/datasets/eSOL/mmseq_outdir/train.csv"
  val_data_path: "/nfs_beijing/kubeflow-user/zhangyang_2024/workspace/protein_benchmark/datasets/eSOL/mmseq_outdir/val.csv"
  test_data_path: "/nfs_beijing/kubeflow-user/zhangyang_2024/workspace/protein_benchmark/datasets/eSOL/mmseq_outdir/test.csv"

Training:
  epoch: 50  # end epoch
  lr: 1e-4  # Learning rate
  lr_scheduler: "cosine"
  check_val_every_n_epoch: 1
  seed: 2024
  batch_size: 64
  num_workers: 4
  seq_len: 1024

Model:
  pretrain_model_name: 'esm2_650m'
  finetune_type: 'adapter'
  lora_r: 8                  # 低秩矩阵的秩
  lora_alpha: 32             # LoRA 的 alpha 参数
  lora_dropout: 0.1          # Dropout 防止过拟合

Task:
  task_name: "eSOL"
  task_type: "regression"
  num_classes: 1
  # metric: "valid_spearman"
  # direction: "max"

hydra:
  output_subdir: null
