csv_path: ./processed_pdb/pdb_metadata.csv
cache_path: .cache/processed_pdb
filtering:
  max_len: 320
  min_len: 60
  # Selects a subset of examples. Useful for debugging.
  subset: null
  allowed_oligomer: [monomeric]
  max_helix_percent: 1.0
  max_loop_percent: 0.5
  min_beta_percent: -1.0
  rog_quantile: 0.96
num_csv_processors: 5
